# Generated by Django 5.0.6 on 2026-05-26 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_category', models.CharField(choices=[('FUEL_COMBUSTION', 'Fuel combustion'), ('ELECTRICITY', 'Purchased electricity'), ('BUSINESS_TRAVEL', 'Business travel'), ('PROCUREMENT', 'Purchased goods')], max_length=32)),
                ('scope', models.CharField(choices=[('S1', 'Scope 1'), ('S2', 'Scope 2'), ('S3', 'Scope 3')], max_length=2)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('quantity_unit', models.CharField(max_length=16)),
                ('normalized_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('normalized_unit', models.CharField(max_length=16)),
                ('emission_factor', models.DecimalField(decimal_places=6, max_digits=18)),
                ('emission_factor_unit', models.CharField(max_length=32)),
                ('emission_amount_kgco2e', models.DecimalField(decimal_places=6, max_digits=18)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('travel_mode', models.CharField(blank=True, max_length=64)),
                ('class_of_travel', models.CharField(blank=True, max_length=64)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('suspicious_flags', models.JSONField(blank=True, default=list)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='ingestion.datasource')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='ingestion.organization')),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='ingestion.rawrecord')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'review_status'], name='emissions_e_organiz_45b444_idx'), models.Index(fields=['organization', 'scope'], name='emissions_e_organiz_cfc59b_idx'), models.Index(fields=['data_source', 'activity_date'], name='emissions_e_data_so_d650f0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='emissionrecord',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='emission_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='emissionrecord',
            constraint=models.CheckConstraint(check=models.Q(('normalized_quantity__gte', 0)), name='emission_normalized_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='emissionrecord',
            constraint=models.CheckConstraint(check=models.Q(('emission_amount_kgco2e__gte', 0)), name='emission_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='emissionrecord',
            constraint=models.CheckConstraint(check=models.Q(('period_end__isnull', True), ('period_start__isnull', True), ('period_end__gte', models.F('period_start')), _connector='OR'), name='emission_period_valid'),
        ),
    ]
