# Generated by Django 5.0.6 on 2026-05-26 12:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('INGESTED', 'Ingested'), ('NORMALIZED', 'Normalized'), ('REVIEWED', 'Reviewed'), ('LOCKED', 'Locked')], max_length=16)),
                ('actor', models.CharField(blank=True, max_length=128)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(blank=True, max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='emissions.emissionrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'occurred_at'], name='reviews_aud_organiz_a0222d_idx'), models.Index(fields=['emission_record', 'occurred_at'], name='reviews_aud_emissio_5c9ba2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('FLAG', 'Flag for review')], max_length=16)),
                ('reviewer_name', models.CharField(max_length=128)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_actions', to='emissions.emissionrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='ingestion.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'created_at'], name='reviews_rev_organiz_f1d2d9_idx'), models.Index(fields=['emission_record', 'created_at'], name='reviews_rev_emissio_bd94c9_idx')],
            },
        ),
    ]
