# Generated by Django 5.0.6 on 2026-05-26 12:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP MM Export'), ('UTILITY', 'Utility Portal'), ('TRAVEL', 'Corporate Travel')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_file_name', models.CharField(blank=True, max_length=255)),
                ('raw_file_sha256', models.CharField(blank=True, max_length=64)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='ingestion.datasource')),
            ],
        ),
        migrations.AddField(
            model_name='datasource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='ingestion.organization'),
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_record_id', models.CharField(blank=True, max_length=128)),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField()),
                ('raw_text', models.TextField(blank=True)),
                ('raw_hash_sha256', models.CharField(blank=True, max_length=64)),
                ('ingest_status', models.CharField(choices=[('RECEIVED', 'Received'), ('PARSED', 'Parsed'), ('NORMALIZED', 'Normalized'), ('ERROR', 'Error')], default='RECEIVED', max_length=16)),
                ('suspicious_flags', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_records', to='ingestion.datasource')),
                ('ingestion_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_records', to='ingestion.ingestionbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['data_source', 'received_at'], name='ingestion_i_data_so_64e2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['organization', 'source_type'], name='ingestion_d_organiz_c6b96d_idx'),
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(fields=('organization', 'source_type', 'name'), name='uniq_datasource_per_org_type_name'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['organization', 'data_source', 'received_at'], name='ingestion_r_organiz_2a65ac_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['raw_hash_sha256'], name='ingestion_r_raw_has_dd8c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['ingest_status'], name='ingestion_r_ingest__c4edc8_idx'),
        ),
    ]
